apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb-secret.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - namegen-deployment.yaml
  - namegen-service.yaml
