apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: namegen
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: genuser
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_INITDB_DATABASE: namegen
